# Generated by Django 3.1.2 on 2021-01-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210110_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(upload_to='Profile_pics', verbose_name='profile pic'),
        ),
    ]
