# Generated by Django 3.1.2 on 2021-01-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210111_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
